### ISSUE TITLE
invariant voilation: the title prop of a button must be a string

### ISSUE THREAD

**Issue by muhammadhaseebsohail** [jasonleibowitz/react-add-to-calendar-hoc#18]
# Bug report
![simulator screen shot - iphone x - 2019-01-08 at 11 09 24](https://user-images.githubusercontent.com/37294317/50812840-17cd4100-1336-11e9-9d4a-a808b43d26ff.png)

My code is :
import AddToCalendarHOC from 'react-add-to-calendar-hoc';
const AddToCalendarDropdown = AddToCalendarHOC(Button, Dropdown);
import moment from 'moment/min/moment-with-locales'

const startDatetime = moment().utc().add(2, 'days');
const endDatetime = startDatetime.clone().add(2, 'hours');
const duration = endDatetime.diff(startDatetime, 'hours');
const event = {
  description: 'Description of event. Going to have a lot of fun doing things that we scheduled ahead of time.',
  duration,
  endDatetime: endDatetime.format('YYYYMMDDTHHmmssZ'),
  location: 'NYC',
  startDatetime: startDatetime.format('YYYYMMDDTHHmmssZ'),
  title: 'Super Fun Event',
}

  render() {
    return (
      <View style={styles.container}>
        <Text style={{color:'black'}}>Calender event start</Text>
        <AddToCalendarDropdown  event={event} optionsOpen/>     
       <Text style={{color:'black'}}>calender event end</Text>
      </View>
    );
  }

Can you please help me out , how can i figure out this?

**Comment by jasonleibowitz** [comment]
Do you have a repo you can link to where this error is happening? It’s kind of hard to figure out what’s going on from the text you posted.

**Comment by muhammadhaseebsohail** [comment]
this is what i am doing  @jasonleibowitz :
import {
    Button,
    Dropdown,
} from "react-native";

import AddToCalendarHOC from 'react-add-to-calendar-hoc';
const AddToCalendarDropdown = AddToCalendarHOC(Button, Dropdown);
const startDatetime = moment().utc().add(2, 'days');
const endDatetime = startDatetime.clone().add(2, 'hours');
const duration = endDatetime.diff(startDatetime, 'hours');
const event = {
description: 'Description of event. Going to have a lot of fun doing things that we scheduled ahead of time.',
duration,
endDatetime: endDatetime.format('YYYYMMDDTHHmmssZ'),
location: 'NYC',
startDatetime: startDatetime.format('YYYYMMDDTHHmmssZ'),
title: 'Super Fun Event',
}

export default class App extends Component{

  render() {
    return (
  <AddToCalendarDropdown
    className={componentStyles}
    linkProps={{
      className: linkStyles,
    }}
    event={event}
  />

    );
  }
}

**Comment by jasonleibowitz** [comment]
Well there’s your issue - this library wasn’t built for React Native. Feel free to fork it, make any changes, and submit a PR if you want to add support for React Native. 

P.S. Check out [this link](
https://help.github.com/articles/creating-and-highlighting-code-blocks) on how to enter code blocks in Github markdown. It makes reading your code significantly easier.

**Comment by muhammadhaseebsohail** [comment]
can you please recommend me a library for this?
i need to copy sessions to gmail/outlook? 
i will be greatfull to you.

**Comment by jasonleibowitz** [comment]
Try googling [react native add to calendar](https://www.google.com/search?q=react+native+add+to+calendar&ie=UTF-8&oe=UTF-8&hl=en-us)?

**Comment by muhammadhaseebsohail** [comment]
acknowledge
