### ISSUE TITLE
Enable to use the library

### ISSUE THREAD

**Issue by memorx** [jasonleibowitz/react-add-to-calendar-hoc#2]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to https://npm.runkit.com/react-add-to-calendar-hoc
2. Click on run
3. Scroll down to the log
4. See error Error: Cannot find module 'prop-types'

## Screenshots
<img width="670" alt="screen shot 2018-06-14 at 3 02 19 pm" src="https://user-images.githubusercontent.com/1566560/41440628-1ce7c642-6fe4-11e8-89e6-ef45707a0b8b.png">
![screen shot 2018-06-14 at 3 02 30 pm](https://user-images.githubusercontent.com/1566560/41440629-1d02e9ae-6fe4-11e8-8ffd-dc29ce436c62.png)

## System information
 - OS: macOS
 - Browser chrome
 - Version of Library: v1.0.3

**Comment by AndrewNatoli** [comment]
This would be resolved by #5 :)

**Comment by jasonleibowitz** [comment]
Published a new version that should fix this. It may take a little time for bundlephobia and npm runkit to update, but this should work now. Reopen this issue if you're still having problems.
