### ISSUE TITLE
URL should be come as part of the Description

### ISSUE THREAD

**Issue by ChandraSannamuri** [jasonleibowitz/react-add-to-calendar-hoc#21]
# Feature request

## Is your feature request related to a problem? Please describe.
The URL information should be Part of the Description

## Describe the solution you'd like
In Outlook, Gmail , Yahoo the url from where the event is getting added to calendar is not coming as part of the event description. If it comes as part of the description it will be good.

## Describe alternatives you've considered
The ics file description should have the URL

**Comment by jasonleibowitz** [comment]
@ChandraSannamuri Can you provide more info please? I don't fully understand your issue. If you're asking about adding a URL in the description, this already behaves as expected. 

You provide the `description` in the event argument. Take a look at the following screenshots:

![Screen Capture on 2019-05-12 at 12-11-07](https://user-images.githubusercontent.com/2746773/57584951-5410d980-74af-11e9-817d-9556af4c39e6.gif)

<img width="449" alt="Screen Shot 2019-05-12 at 12 10 33 PM" src="https://user-images.githubusercontent.com/2746773/57584955-6559e600-74af-11e9-8467-06c6a0376397.png">

**Comment by ChandraSannamuri** [comment]
Yes you are right it is working with react-add-to-calendar-hoc but did not worked with react-add-to-calendar. i have posted at wrong place.
