### ISSUE TITLE
Object.values is incompatible with IE11

### ISSUE THREAD

**Issue by KenneyE** [jasonleibowitz/react-add-to-calendar-hoc#23]
# Bug report

## Describe the bug
The package is incompatible with IE11 due to the usage of `Object.values`. With this package included in my application, I receive the following error when testing on IE11 in Browserstack:
`Object doesn’t support property or method ‘values’`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Use this package in a React application
2. Load the application in IE11

## Screenshots
![Screen Shot 2019-05-29 at 10 09 26 AM](https://user-images.githubusercontent.com/5776842/58572938-e1676400-81f9-11e9-98c6-3652d8b837c2.png)

## System information
 - OS: BrowserStack 
 - Browser: IE11
 - Version of Library: 1.0.8

## Additional context

I have a fork replacing all of the instances of `Object.values` with and IE11 compatible code snippet. I'll attach the PR to this issue.

**Comment by jasonleibowitz** [comment]
This will be included in 1.0.9
