### ISSUE TITLE
Set your own filename on .ics files

### ISSUE THREAD

**Issue by juhaniahola** [jasonleibowitz/react-add-to-calendar-hoc#29]
# Feature request

It would be great to be able to set your own filename to .ics files instead of generic download.ics

**Comment by jasonleibowitz** [comment]
@aholajuhani Thanks for the suggestion. That shouldn’t be too difficult to implement. Do you want to give it a shot and open a PR?

**Comment by juhaniahola** [comment]
@jasonleibowitz sure!

**Comment by jasonleibowitz** [comment]
Resolved by #30

**Comment by jasonleibowitz** [comment]
@aholajuhani I'll push a new release later today.
