### ISSUE TITLE
Doesn't work in next.js project

### ISSUE THREAD

**Issue by ojelicoder** [jasonleibowitz/react-add-to-calendar-hoc#52]
Hello there,
<img width="1091" alt="Screen Shot 2021-05-28 at 02 28 43" src="https://user-images.githubusercontent.com/20795143/119908975-770a6b00-bf5c-11eb-85ae-f912b085676a.png">

I'm adding to my Next.js project as follows.
import AddToCalendarHOC from 'react-add-to-calendar-hoc';

const AddToCalendarModal = AddToCalendarHOC (Button, CalendarModal),
isiOS = /iPad|iPhone|iPod/.test(navigator.userAgent),
[event, setEvent] = useState (null);
useEffect(() => {
        const startDatetime = moment (). utc (). add (2, 'days'),
        endDatetime = startDatetime.clone (). add (2, 'hours'),
        duration = moment.duration(endDatetime.diff(startDatetime)).asHours();

        const event = {
            description: 'Description of event. Going to have a lot of fun doing things that we scheduled ahead of time.',
            duration,
            endDatetime: endDatetime.format('YYYYMMDDTHHmmssZ'),
            location: 'NYC',
            startDatetime: startDatetime.format ('YYYYMMDDTHHmmssZ'),
            title: 'Super Fun Event',
        }

        setEvent (event);
    })

and I am getting error as below.
ReferenceError: CalendarModal is not defined

Can you help me?

**Comment by jasonleibowitz** [comment]
Yea, that's because you never imported or defined `CalendarModal`. If you look at the [code of the examples](https://github.com/jasonleibowitz/react-add-to-calendar-hoc/blob/master/src/docs/index.jsx#L101), you'll see that `CalendarModal` is imported [here](https://github.com/jasonleibowitz/react-add-to-calendar-hoc/blob/master/src/docs/index.jsx#L8).

I just created a _very simple_ CalendarModal as an example, but as this is a HOC, you should use whatever component you want. The CalendarModal example uses [react-modal](https://github.com/reactjs/react-modal).

**Comment by ojelicoder** [comment]
Hi @jasonleibowitz ,

Thank you so much for your answer..  Yes, when I add a modal, this error is gone, but the modal does not open. You can see it in the screenshot. Where exactly am I going wrong?

<img width="1059" alt="Screen Shot 2021-05-28 at 12 35 36" src="https://user-images.githubusercontent.com/20795143/119963842-3ab52a00-bfb1-11eb-8f50-ce9296151937.png">
<img width="1343" alt="Screen Shot 2021-05-28 at 12 36 42" src="https://user-images.githubusercontent.com/20795143/119964098-81a31f80-bfb1-11eb-93fc-cdf2a0c5f2a8.png">
<img width="1298" alt="Screen Shot 2021-05-28 at 12 37 05" src="https://user-images.githubusercontent.com/20795143/119964061-73550380-bfb1-11eb-8b6e-b3402df2080e.png">

**Comment by ojelicoder** [comment]
Hi @jasonleibowitz,

After a few edits I see it working. 

Thank you so much.

<img width="1169" alt="Screen Shot 2021-07-16 at 16 38 16" src="https://user-images.githubusercontent.com/20795143/125957863-7ad8cdbf-0b0d-4b22-b36f-ce5dfbac87ec.png">

**Comment by ojelicoder** [comment]
Hi @jasonleibowitz,

After a few edits I see it working.

Thank you so much.

<img width="1169" alt="Screen Shot 2021-07-16 at 16 38 16" src="https://user-images.githubusercontent.com/20795143/125958248-198a5db8-798f-4e0f-ba72-86db2d45cd21.png">
